import Layout from '@/components/Layout'
import Head from 'next/head'
import Image from 'next/image'
import profilepic from '../../public/images/profile/profile-port-hd.png'
import AnimatedText from '@/components/AnimatedText'
import { motion } from "framer-motion";

export default function Home() {
  return (
    <>
      <Head>
        <title>Portfolio - Pedro Frasson</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className='flex items-center text-dark w-full min-h-screen'>
        <Layout className='pt-0'>
          <div className="flex items-center justify-between w-full">
            <div className='w-1/2'>
              <Image src={profilepic} alt='PedroFrasson' className='w-full h-auto shadow-xl' />
            </div>
            <div className='w-1/2 p-6 flex flex-col items-center self-center'>
              <AnimatedText text="Escrevendo o Futuro com Linhas de Código." className='!text-6xl !text-left' />
              <motion.p whileHover={{ y: -5 }} className='my-4 text-base font-medium'
              >
                Trilhando meu Caminho como desenvolvedor de Software,  com Aprendizado Contínuo e Comprometimento.
              </motion.p>
            </div>
          </div>
        </Layout>
      </main>
    </>
  )
}